{% set version = "1.11" %}

package:
  name: sat-bsa
  version: {{ version }}

source:
  url: https://github.com/SegawaTenta/Sat-BSA/releases/download/v{{ version }}/Sat-BSA-{{ version }}.tar.gz
  sha256: 003c5642485e17a50a497b81ff2f83d1ced63dd1370736744365f66e458256f6

build:
  noarch: generic
  number: 0

requirements:
  run:
    - python
    - samtools =1.9
    - minimap2 =2.17
    - r-base
    - perl
    - openjdk

test:
  commands:
    - Sat-BSA -h

about:
  home: https://github.com/SegawaTenta/Sat-BSA
  summary: 'Sat-BSA is a package used for applying local de novo assembly and identifying the structural variants in the assembled region'
  license: 'GPL-3.0-or-later'
  license_family: GPL

extra:
  identifiers:
    - biotools:sta-bsa
